from django.conf.urls import patterns, include, url
from django.contrib import admin
from onadata.apps.hcmp_report import views

urlpatterns = patterns('',
                       url(r'^tb_hiv/$', views.tb_hiv, name='tb_hiv'),
                       url(r'^get_geodata/(?P<tag>[^/]+)/$', views.get_geodata, name='get_geodata'),
                       url(r'^get_tb_hiv_data_table/$', views.get_tb_hiv_data_table, name='get_tb_hiv_data_table'),
                       url(r'^malaria/$', views.malaria, name='tb_hiv'),
                       url(r'^get_malaria_data_table/$', views.get_malaria_data_table, name='get_malaria_data_table'),
                       url(r'^immunization/$', views.immunization, name='immunization'),
                       url(r'^get_immunization_data_table/$', views.get_immunization_data_table,
                           name='get_immunization_data_table'),
                       url(r'^outbreak_disease/$', views.outbreak_disease, name='outbreak_disease'),
                       url(r'^get_outbreak_disease_data_table/$', views.get_outbreak_disease_data_table,
                           name='get_outbreak_disease_data_table'),
                       url(r'^health/$', views.health, name='health'),
                       url(r'^get_health_data_table/$', views.get_health_data_table, name='get_health_data_table'),
                       url(r'^wfp_nutrition/$', views.wfp_nutrition, name='wfp_nutrition'),
                       url(r'^get_wfp_nutrition_data_table/$', views.get_wfp_nutrition_data_table,
                           name='get_wfp_nutrition_data_table'),
                       url(r'^unicef_nutrition/$', views.unicef_nutrition, name='unicef_nutrition'),
                       url(r'^get_unicef_nutrition_data_table/$', views.get_unicef_nutrition_data_table,
                           name='get_unicef_nutrition_data_table'),
                       url(r'^education_student/$', views.education_student, name='education_student'),
                       url(r'^get_education_student_data_table/$', views.get_education_student_data_table,
                           name='get_education_student_data_table'),
                       url(r'^education_teacher/$', views.education_teacher, name='education_teacher'),
                       url(r'^get_education_teacher_data_table/$', views.get_education_teacher_data_table,
                           name='get_education_teacher_data_table'),
                       url(r'^wash/$', views.wash, name='wash'),
                       url(r'^get_wash_data_table/$', views.get_wash_data_table, name='get_wash_data_table'),
                       url(r'^agriculture_fdmn/$', views.agriculture_fdmn, name='agriculture_fdmn'),
                       url(r'^get_agriculture_fdmn_data_table/$', views.get_agriculture_fdmn_data_table,
                           name='get_agriculture_fdmn_data_table'),
                       url(r'^agriculture_host/$', views.agriculture_host, name='agriculture_host'),
                       url(r'^get_agriculture_host_data_table/$', views.get_agriculture_host_data_table,
                           name='get_agriculture_host_data_table'),
                       url(r'^cfs_fdmn/$', views.cfs_fdmn, name='cfs_fdmn'),
                       url(r'^get_cfs_fdmn_data_table/$', views.get_cfs_fdmn_data_table,
                           name='get_cfs_fdmn_data_table'),
                       url(r'^cfs_host/$', views.cfs_host, name='cfs_host'),
                       url(r'^get_cfs_host_data_table/$', views.get_cfs_host_data_table,
                           name='get_cfs_host_data_table'),
                       url(r'^cfs_summary/$', views.cfs_summary, name='cfs_summary/'),
                       url(r'^get_cfs_summary_data_table/$', views.get_cfs_summary_data_table,
                           name='get_cfs_summary_data_table'),
                       url(r'^pss/$', views.pss, name='pss'),
                       url(r'^get_pss_data_table/$', views.get_pss_data_table, name='get_pss_data_table'),
                       url(r'^c4d/$', views.c4d, name='c4d'),
                       url(r'^get_c4d_data_table/$', views.get_c4d_data_table, name='get_c4d_data_table'),
                       url(r'^gbv/$', views.gbv, name='gbv'),
                       url(r'^get_gbv_data_table/$', views.get_gbv_data_table, name='get_gbv_data_table'),

                       # ------------ Emtiaz (S) ----------------

                       url(r'^activity_progress_report/$', views.activity_progress_report, name='activity_progress_report'),
                       url(r'^get_activity_progress_report_table/$', views.get_activity_progress_report_table,
                           name='get_activity_progress_report_table'),
                       url(r'^get_union_list/$', views.get_union_list, name='get_union_list'),
                       url(r'^get_camp_list/$', views.get_camp_list, name='get_camp_list'),

                       url(r'^sector/$', views.sector, name='sector'),
                       url(r'^create_sector/$', views.create_sector, name='create_sector'),

                       url(r'^activity_progress_edit/(?P<id_string>[^/]+)/(?P<instance_id>\d+)/$', views.activity_progress_edit, name='activity_progress_edit'),


                       url(r'^get_opt_activity_list/(?P<id_string>[^/]+)/(?P<donor>[^/]+)/$', views.get_opt_activity_list, name='get_opt_activity_list'),
                       url(r'^get_opt_sub_activity_list/(?P<id_string>[^/]+)/(?P<donor>[^/]+)/(?P<activity>[^/]+)/$',
                           views.get_opt_sub_activity_list, name='get_opt_sub_activity_list'),

                       url(r'^get_opt_project_list/(?P<id_string>[^/]+)/(?P<donor>[^/]+)/(?P<activity>[^/]+)/(?P<sub_activity>[^/]+)/$',
                           views.get_opt_project_list, name='get_opt_project_list'),

                       # ------------ Emtiaz (E) ----------------


                       url(r'^nfi_fdmn/$', views.nfi_fdmn, name='nfi_fdmn'),
                       url(r'^get_nfi_fdmn_data_table/$', views.get_nfi_fdmn_data_table,
                           name='get_nfi_fdmn_data_table'),

                       url(r'^nfi_host/$', views.nfi_host, name='nfi_host'),
                       url(r'^get_nfi_host_data_table/$', views.get_nfi_host_data_table,
                           name='get_nfi_host_data_table'),

                       url(r'^drr_nfi/$', views.drr_nfi, name='drr_nfi'),
                       url(r'^get_drr_nfi_data_table/$', views.get_drr_nfi_data_table, name='get_drr_nfi_data_table'),
                       url(r'^drr_wash/$', views.drr_wash, name='drr_wash'),
                       url(r'^get_drr_wash_data_table/$', views.get_drr_wash_data_table,
                           name='get_drr_wash_data_table'),
                       url(r'^training/$', views.training, name='training'),
                       url(r'^get_training_data_table/$', views.get_training_data_table,
                           name='get_training_data_table'),
                       url(r'^site_management/$', views.site_management, name='site_management'),
                       url(r'^get_site_management_data_table/$', views.get_site_management_data_table,
                           name='get_site_management_data_table'),
                       url(r'^meeting/$', views.meeting, name='meeting'),
                       url(r'^get_meeting_data_table/$', views.get_meeting_data_table, name='get_meeting_data_table'),
                       url(r'^visitor/$', views.visitor, name='visitor'),
                       url(r'^get_visitor_data_table/$', views.get_visitor_data_table, name='get_visitor_data_table'),
                       url(r'^branch_list/$', views.branch_list,
                           name='branch_list'),
                       url(r'^add_branch_form/$', views.add_branch_form,
                           name='add_branch_form'),
                       url(r'^edit_branch_form/(?P<branch_id>\d+)/$', views.edit_branch_form,
                           name='edit_branch_form'),
                       url(r'^delete_branch/(?P<branch_id>\d+)/$', views.delete_branch,
                           name='delete_branch'),
                       url(r'^camp_list/$', views.camp_list,
                           name='camp_list'),
                       url(r'^add_camp_form/$', views.add_camp_form,
                           name='add_camp_form'),
                       url(r'^edit_camp_form/(?P<camp_id>\d+)/$', views.edit_camp_form,
                           name='edit_camp_form'),
                       url(r'^delete_camp/(?P<camp_id>\d+)/$', views.delete_camp,
                           name='delete_camp'),
                       url(r'^get_geolocation_csv/(?P<id_string>[^/]+)/$', views.get_geolocation_csv),

                       url(r'^donor/$', views.donor, name="donor"),
                       url(r'^donorCreate/$', views.donorCreate, name="donorCreate"),
                       url(r'^donor_Edit/$', views.donor_Edit, name="donor_Edit"),
                       url(r'^donor_Delete/(?P<donor_id>\d+)/$', views.donor_Delete, name="donor_Delete"),
                       url(r'^getUpazilas/$', views.getUpazilas, name="getUpazilas"),
                       url(r'^getUnions/$', views.getUnions, name="getUnions"),
                       url(r'^getCamp/$', views.getCamp, name="getCamp"),
                       url(r'^shelter_nfi_daily_report/$', views.shelter_nfi_daily_report, name="shelter_nfi_daily_report"),
                       url(r'^get_report_shelter_nfi_daily_report/$', views.get_report_shelter_nfi_daily_report, name="get_report_shelter_nfi_daily_report"),
                       url(r'^shelter_nfi_monthly_report/$', views.shelter_nfi_monthly_report, name="shelter_nfi_monthly_report"),
                       url(r'^get_report_shelter_nfi_monthly_report/$', views.get_report_shelter_nfi_monthly_report, name="get_report_shelter_nfi_monthly_report"),
                       url(r'^get_border_transit_location/$', views.get_border_transit_location, name="get_border_transit_location"),
                       url(r'^getActivityMapValidation/$', views.getActivityMapValidation, name="getActivityMapValidation"),

                       # ------------------- Configuration ------------------------------------------#
                    url(r'^sector_list/$', views.sector_list, name='sector_list'),
                    url(r'^project/(?P<sector_id>\d+)/$', views.project,name='project'),
                    url(r'^get_project/(?P<sector_id>\d+)/$', views.get_project,name='get_project'),
                    url(r'^activity-list/(?P<sector_id>\d+)/$', views.activity_list, name='activity_list'),
                    url(r'^add-activity/(?P<sector_id>\d+)/$', views.add_activity, name='add_activity'),
                    url(r'^subactivity_list/(?P<activity_id>\d+)/$', views.subactivity_list, name='subactivity_list'),
                    url(r'^add_subactivity/(?P<activity_id>\d+)/$', views.add_subactivity, name='add_subactivity'),
                    url(r'^activity-map-list/(?P<subactivity_id>\d+)/$', views.activity_map_list, name='activity_map_list'),
                    url(r'^add-activity-map/(?P<subactivity_id>\d+)/$', views.add_activity_map, name='add_activity_map'),
                    url(r'^check_duplicate_activity_code/$', views.check_duplicate_activity_code, name='check_duplicate_activity_code'),
                    url(r'^check_duplicate_sub_activity_code/$', views.check_duplicate_sub_activity_code, name='check_duplicate_sub_activity_code'),
                    url(r'^get_export/$', views.get_export, name='get_export'),

                    # ------------------- API ------------------------------------------#
                    url(r'^get_activity_csv/(?P<id_string>[^/]+)/$', views.get_activity_csv, name='get_activity_csv'),


                       )
